spring:
  config:
    activate:
      on-profile: "proddb"
  datasource:
    url: jdbc:mysql://mind-jelly-db.cjuqocwecju5.ap-northeast-2.rds.amazonaws.com:3306/mind-jelly-db?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 'mindjelly0116'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.hbm2ddl.auto: update
#    hibernate:
#      ddl-auto: update
    show-sql: true