spring:
  config:
    activate:
      on-profile: "dockerdb"
  datasource:
    url: jdbc:mysql://db:3306/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
    show-sql: true
