spring:
  profiles:
    group:
      "prod": "proddb,common,security"
    active: prod

---

spring:
  config:
    activate:
      on-profile: "common"
  sql:
    init:
      mode: always
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  server:
    tomcat:
      connection-timeout: 5000

scheduler:
  time: "0 0 7 * * *"

---

spring:
  config:
    activate:
      on-profile: "security"
  mail:
    host: smtp.gmail.com
    port: '587'
    username: wlsgur348@gmail.com
    password: oxctettjpfzocaeu
    properties.mail.smtp:
      auth: true
      starttls.enable: true

---